# Generated by Django 4.1 on 2022-09-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.FloatField(blank=True, null=True)),
                ('endTime', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('startTime', models.FloatField(blank=True, null=True)),
                ('endTime', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('professor', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('examDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='sharitz.examdate')),
                ('weeklySchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week', to='sharitz.weeklyschedule')),
            ],
        ),
    ]
