# Generated by Django 4.1.1 on 2022-10-16 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['college'],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.IntegerField(blank=True, null=True)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('start', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('professor', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharitz.college')),
                ('examDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontExam', to='sharitz.examdate')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choise', to=settings.AUTH_USER_MODEL)),
                ('ws', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontWeek', to='sharitz.ws')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('professor', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('requirement', models.CharField(blank=True, default='ندارد', max_length=256)),
                ('synthesis', models.CharField(blank=True, default='ندارد', max_length=256)),
                ('ps', models.CharField(blank=True, default='ندارد', max_length=256)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharitz.college')),
                ('examDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backExam', to='sharitz.examdate')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ws', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backWeek', to='sharitz.ws')),
            ],
        ),
    ]
