# Generated by Django 4.1.1 on 2022-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ps',
            field=models.CharField(blank=True, default='ندارد', max_length=256, null=True),
        ),
    ]
