# Generated by Django 4.1.1 on 2022-10-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharitz', '0003_alter_course_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchoise',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchoise',
            name='ps',
            field=models.CharField(blank=True, default='ندارد', max_length=256),
        ),
        migrations.AddField(
            model_name='studentchoise',
            name='requirement',
            field=models.CharField(blank=True, default='ندارد', max_length=256),
        ),
        migrations.AddField(
            model_name='studentchoise',
            name='synthesis',
            field=models.CharField(blank=True, default='ندارد', max_length=256),
        ),
        migrations.AlterField(
            model_name='studentchoise',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
