# Generated by Django 4.1.1 on 2022-10-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0004_alter_studentchoise_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchoise',
            name='courseId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
