# Generated by Django 4.1 on 2022-09-03 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharitz', '0005_rename_day_weeklyschedule_day0_weeklyschedule_day1'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('professor', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('examDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontExam', to='sharitz.examdate')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choise', to=settings.AUTH_USER_MODEL)),
                ('weeklySchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontWeek', to='sharitz.weeklyschedule')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='examDate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backExam', to='sharitz.examdate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='weeklySchedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backWeek', to='sharitz.weeklyschedule'),
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
