# Generated by Django 4.1 on 2022-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0006_studentchoise_alter_course_examdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentchoise',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
