# Generated by Django 4.1.1 on 2022-09-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0007_course_unit_studentchoise_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharitz.college'),
        ),
        migrations.AlterField(
            model_name='studentchoise',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharitz.college'),
        ),
    ]
