# Generated by Django 4.1.1 on 2022-10-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0007_college_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='user',
        ),
    ]
