# Generated by Django 4.1.1 on 2022-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0008_remove_college_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
