# Generated by Django 4.1.1 on 2022-10-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0010_alter_college_id_alter_course_id_alter_examdate_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['college']},
        ),
    ]
