# Generated by Django 4.1.1 on 2022-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0011_alter_college_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college',
            field=models.CharField(default='', max_length=256),
        ),
    ]
