# Generated by Django 4.1.1 on 2022-10-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0013_alter_college_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='day0',
            new_name='day2',
        ),
    ]
