# Generated by Django 4.1.1 on 2022-10-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0014_rename_day0_weeklyschedule_day2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdate',
            old_name='endTime',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='examdate',
            old_name='startTime',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='endTime',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='startTime',
            new_name='time',
        ),
    ]
