# Generated by Django 4.1.1 on 2022-10-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0016_rename_weeklyschedule_ws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='weeklySchedule',
            new_name='ws',
        ),
        migrations.RenameField(
            model_name='studentchoise',
            old_name='weeklySchedule',
            new_name='ws',
        ),
    ]
