# Generated by Django 4.1.1 on 2022-10-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharitz', '0017_rename_weeklyschedule_course_ws_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdate',
            name='time',
        ),
    ]
